// EncryptTool/Program.cs
using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using Newtonsoft.Json; // (FTP 정보 JSON 직렬화)
using Npgsql; // (NpgsqlConnectionStringBuilder)

namespace EncryptTool
{
    /// <summary>
    /// FTP 접속 정보를 직렬화하기 위한 DTO (Data Transfer Object)
    /// (ConnectInfo.dll의 FtpConfig와 동일한 구조여야 함)
    /// </summary>
    internal class FtpConfig
    {
        public string Host { get; set; }
        public int Port { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }

    class Program
    {
        // "공용 키" (ConnectInfo.dll의 키와 100% 동일해야 함)
        private const string AES_COMMON_KEY = "itm-agent-v1-secret";

        static void Main(string[] args)
        {
            Console.WriteLine("--- ITM Agent Connection.ini 암호화 생성 도구 ---");
            Console.WriteLine("배포용 Connection.ini 파일을 생성합니다.");

            // 1. (구)서버의 평문 정보를 이곳에 정확하게 입력합니다.
            // (Database)
            string dbHost = "10.0.0.1"; // (구)DB IP
            string dbPort = "5432";
            string dbUser = "userid";
            string dbPass_PLAIN = "plain_db_password"; // (구)DB 평문 암호
            string dbName = "itm";

            // (FTPS)
            string ftpHost = "10.0.0.1"; // (구)FTP IP
            string ftpPort = "21";
            string ftpUser = "itm_agent_user";
            string ftpPass_PLAIN = "plain_ftp_password"; // (구)FTP 평문 암호
            // (ftpPath는 ConnectInfo.dll에 하드코딩하기로 함)

            // -----------------------------------------------------------------

            try
            {
                // 2. DB 연결 문자열 (평문) 생성
                var csBuilder = new NpgsqlConnectionStringBuilder
                {
                    Host = dbHost,
                    Port = int.Parse(dbPort ?? "5432"),
                    Username = dbUser,
                    Password = dbPass_PLAIN, // (평문 암호 포함)
                    Database = dbName,
                    Encoding = "UTF8",
                    SslMode = SslMode.Disable,
                    SearchPath = "public"
                };
                string dbConfigString = csBuilder.ConnectionString;

                // 3. FTP 설정 (JSON 평문) 생성
                var ftpConfig = new FtpConfig
                {
                    Host = ftpHost,
                    Port = int.Parse(ftpPort ?? "21"),
                    Username = ftpUser,
                    Password = ftpPass_PLAIN // (평문 암호 포함)
                };
                string ftpConfigString = JsonConvert.SerializeObject(ftpConfig);

                // 4. 각각 공용 키(AES)로 암호화
                string encryptedDbConfig = EncryptAES(dbConfigString, AES_COMMON_KEY);
                string encryptedFtpConfig = EncryptAES(ftpConfigString, AES_COMMON_KEY);

                // 5. 새로운 Connection.ini 파일 내용 생성
                StringBuilder sb = new StringBuilder();
                sb.AppendLine("; ITM Agent Connection Settings (Encrypted by EncryptTool)");
                sb.AppendLine("; Do not edit this file manually.");
                sb.AppendLine();
                sb.AppendLine("[Database]");
                sb.AppendLine($"Config = {encryptedDbConfig}");
                sb.AppendLine();
                sb.AppendLine("[Ftps]");
                sb.AppendLine($"Config = {encryptedFtpConfig}");

                // 6. Connection.ini 파일로 저장
                // (이 EncryptTool.exe가 실행되는 폴더(예: bin/Debug)에 생성됨)
                string outputPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Connection.ini");
                File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);

                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine($"성공! '{outputPath}' 파일이 생성되었습니다.");
                Console.ResetColor();
                Console.WriteLine("이 Connection.ini 파일을 ITM_Agent 설치 패키지에 포함하세요.");
            }
            catch (Exception ex)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine($"[오류] 암호화 또는 파일 생성에 실패했습니다.");
                Console.WriteLine(ex.Message);
                Console.ResetColor();
            }

            Console.WriteLine("엔터 키를 누르면 종료됩니다...");
            Console.ReadLine();
        }

        /// <summary>
        /// (ConnectInfo.dll의 DecryptAES와 호환됨)
        /// AES-256 CBC로 평문 텍스트를 암호화하고 Base64(IV + CipherText)로 반환합니다.
        /// </summary>
        private static string EncryptAES(string plainText, string keyString)
        {
            // 1. 키 해시 (SHA256) -> 32바이트 키 생성
            byte[] keyBytes;
            using (var sha = SHA256.Create())
            {
                keyBytes = sha.ComputeHash(Encoding.UTF8.GetBytes(keyString));
            }

            // 2. AesManaged (C# 7.3)
            using (var aes = new AesManaged())
            {
                aes.Key = keyBytes;
                aes.Mode = CipherMode.CBC;
                aes.Padding = PaddingMode.PKCS7;

                // 3. 새 랜덤 IV (16바이트) 생성
                aes.GenerateIV();
                byte[] iv = aes.IV;

                // 4. 암호화 수행
                byte[] cipherBytes;
                using (var encryptor = aes.CreateEncryptor(aes.Key, aes.IV))
                using (var ms = new MemoryStream())
                {
                    using (var cs = new CryptoStream(ms, encryptor, CryptoStreamMode.Write))
                    using (var sw = new StreamWriter(cs))
                    {
                        sw.Write(plainText);
                    }
                    cipherBytes = ms.ToArray();
                }

                // 5. 최종 결과물: [16바이트 IV] + [암호문]
                byte[] fullCipher = new byte[iv.Length + cipherBytes.Length];
                Buffer.BlockCopy(iv, 0, fullCipher, 0, iv.Length);
                Buffer.BlockCopy(cipherBytes, 0, fullCipher, iv.Length, cipherBytes.Length);

                // 6. Base64로 변환하여 반환
                return Convert.ToBase64String(fullCipher);
            }
        }
    }
}
